-- schema.sql

CREATE TABLE `users` (
  `uuid` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `phone_number` varchar(13) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `phone_number` (`phone_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `rotations` (
  `uuid` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `start_date` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `rotation_details` (
  `rotation_uuid` varchar(255) NOT NULL,
  `order_id` int(11) unsigned NOT NULL,
  `shift_uuid` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`rotation_uuid`,`order_id`,`shift_uuid`),
  KEY `rotation_uuid` (`rotation_uuid`),
  KEY `shift_uuid` (`shift_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `shifts` (
  `uuid` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `user_uuid` varchar(255) NOT NULL,
  `monday_0000` tinyint(1) NOT NULL DEFAULT 0,
  `monday_0100` tinyint(1) NOT NULL DEFAULT 0,
  `monday_0200` tinyint(1) NOT NULL DEFAULT 0,
  `monday_0300` tinyint(1) NOT NULL DEFAULT 0,
  `monday_0400` tinyint(1) NOT NULL DEFAULT 0,
  `monday_0500` tinyint(1) NOT NULL DEFAULT 0,
  `monday_0600` tinyint(1) NOT NULL DEFAULT 0,
  `monday_0700` tinyint(1) NOT NULL DEFAULT 0,
  `monday_0800` tinyint(1) NOT NULL DEFAULT 0,
  `monday_0900` tinyint(1) NOT NULL DEFAULT 0,
  `monday_1000` tinyint(1) NOT NULL DEFAULT 0,
  `monday_1100` tinyint(1) NOT NULL DEFAULT 0,
  `monday_1200` tinyint(1) NOT NULL DEFAULT 0,
  `monday_1300` tinyint(1) NOT NULL DEFAULT 0,
  `monday_1400` tinyint(1) NOT NULL DEFAULT 0,
  `monday_1500` tinyint(1) NOT NULL DEFAULT 0,
  `monday_1600` tinyint(1) NOT NULL DEFAULT 0,
  `monday_1700` tinyint(1) NOT NULL DEFAULT 0,
  `monday_1800` tinyint(1) NOT NULL DEFAULT 0,
  `monday_1900` tinyint(1) NOT NULL DEFAULT 0,
  `monday_2000` tinyint(1) NOT NULL DEFAULT 0,
  `monday_2100` tinyint(1) NOT NULL DEFAULT 0,
  `monday_2200` tinyint(1) NOT NULL DEFAULT 0,
  `monday_2300` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_0000` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_0100` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_0200` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_0300` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_0400` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_0500` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_0600` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_0700` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_0800` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_0900` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_1000` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_1100` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_1200` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_1300` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_1400` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_1500` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_1600` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_1700` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_1800` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_1900` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_2000` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_2100` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_2200` tinyint(1) NOT NULL DEFAULT 0,
  `tuesday_2300` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_0000` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_0100` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_0200` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_0300` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_0400` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_0500` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_0600` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_0700` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_0800` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_0900` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_1000` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_1100` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_1200` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_1300` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_1400` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_1500` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_1600` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_1700` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_1800` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_1900` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_2000` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_2100` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_2200` tinyint(1) NOT NULL DEFAULT 0,
  `wednesday_2300` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_0000` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_0100` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_0200` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_0300` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_0400` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_0500` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_0600` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_0700` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_0800` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_0900` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_1000` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_1100` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_1200` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_1300` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_1400` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_1500` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_1600` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_1700` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_1800` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_1900` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_2000` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_2100` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_2200` tinyint(1) NOT NULL DEFAULT 0,
  `thursday_2300` tinyint(1) NOT NULL DEFAULT 0,
  `friday_0000` tinyint(1) NOT NULL DEFAULT 0,
  `friday_0100` tinyint(1) NOT NULL DEFAULT 0,
  `friday_0200` tinyint(1) NOT NULL DEFAULT 0,
  `friday_0300` tinyint(1) NOT NULL DEFAULT 0,
  `friday_0400` tinyint(1) NOT NULL DEFAULT 0,
  `friday_0500` tinyint(1) NOT NULL DEFAULT 0,
  `friday_0600` tinyint(1) NOT NULL DEFAULT 0,
  `friday_0700` tinyint(1) NOT NULL DEFAULT 0,
  `friday_0800` tinyint(1) NOT NULL DEFAULT 0,
  `friday_0900` tinyint(1) NOT NULL DEFAULT 0,
  `friday_1000` tinyint(1) NOT NULL DEFAULT 0,
  `friday_1100` tinyint(1) NOT NULL DEFAULT 0,
  `friday_1200` tinyint(1) NOT NULL DEFAULT 0,
  `friday_1300` tinyint(1) NOT NULL DEFAULT 0,
  `friday_1400` tinyint(1) NOT NULL DEFAULT 0,
  `friday_1500` tinyint(1) NOT NULL DEFAULT 0,
  `friday_1600` tinyint(1) NOT NULL DEFAULT 0,
  `friday_1700` tinyint(1) NOT NULL DEFAULT 0,
  `friday_1800` tinyint(1) NOT NULL DEFAULT 0,
  `friday_1900` tinyint(1) NOT NULL DEFAULT 0,
  `friday_2000` tinyint(1) NOT NULL DEFAULT 0,
  `friday_2100` tinyint(1) NOT NULL DEFAULT 0,
  `friday_2200` tinyint(1) NOT NULL DEFAULT 0,
  `friday_2300` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_0000` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_0100` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_0200` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_0300` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_0400` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_0500` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_0600` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_0700` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_0800` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_0900` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_1000` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_1100` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_1200` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_1300` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_1400` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_1500` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_1600` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_1700` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_1800` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_1900` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_2000` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_2100` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_2200` tinyint(1) NOT NULL DEFAULT 0,
  `saturday_2300` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_0000` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_0100` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_0200` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_0300` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_0400` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_0500` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_0600` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_0700` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_0800` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_0900` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_1000` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_1100` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_1200` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_1300` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_1400` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_1500` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_1600` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_1700` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_1800` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_1900` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_2000` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_2100` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_2200` tinyint(1) NOT NULL DEFAULT 0,
  `sunday_2300` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`),
  UNIQUE KEY `name_user_uuid` (`name`,`user_uuid`),
  KEY `user_uuid` (`user_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `overrides` (
  `uuid` varchar(255) NOT NULL,
  `rotation_uuid` varchar(255) NOT NULL,
  `date` varchar(255) NOT NULL,
  `hour` varchar(255) NOT NULL,
  `user_uuid` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`),
  KEY `user_uuid` (`user_uuid`),
  KEY `rotation_uuid` (`rotation_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `additionals` (
  `uuid` varchar(255) NOT NULL,
  `rotation_uuid` varchar(255) NOT NULL,
  `date` varchar(255) NOT NULL,
  `hour` varchar(255) NOT NULL,
  `user_uuid` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`),
  KEY `user_uuid` (`user_uuid`),
  KEY `rotation_uuid` (`rotation_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `reduces` (
  `uuid` varchar(255) NOT NULL,
  `rotation_uuid` varchar(255) NOT NULL,
  `date` varchar(255) NOT NULL,
  `hour` varchar(255) NOT NULL,
  `user_uuid` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`),
  KEY `user_uuid` (`user_uuid`),
  KEY `rotation_uuid` (`rotation_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
